import type { NewWordInput } from '@/types'

/**
 * 新規アカウント作成時に自動生成する、お試し・チュートリアル用の単語帳。
 * 内容は `英検３級　単語リスト - シート1.csv`（プロジェクトルート）の転記。
 */
export const DEFAULT_TANCHOU_NAME = '英検３級'

export const DEFAULT_TANCHOU_WORDS: NewWordInput[] = [
  { word: 'accident', meaning: '事故、事件', note: '名詞' },
  { word: 'activity', meaning: '活動', note: '名詞' },
  { word: 'advice', meaning: '助言、アドバイス', note: '名詞' },
  { word: 'airplane', meaning: '飛行機', note: '名詞' },
  { word: 'area', meaning: '地域、面積', note: '名詞' },
  { word: 'article', meaning: '記事', note: '名詞' },
  { word: 'artist', meaning: '芸術家、アーティスト', note: '名詞' },
  { word: 'attention', meaning: '注意、注目', note: '名詞' },
  { word: 'beach', meaning: '海岸、浜辺', note: '名詞' },
  { word: 'building', meaning: '建物、ビル', note: '名詞' },
  { word: 'calendar', meaning: 'カレンダー、暦', note: '名詞' },
  { word: 'chance', meaning: '機会、チャンス', note: '名詞' },
  { word: 'climate', meaning: '気候', note: '名詞' },
  { word: 'company', meaning: '会社、仲間', note: '名詞' },
  { word: 'culture', meaning: '文化', note: '名詞' },
  { word: 'custom', meaning: '習慣、風習', note: '名詞' },
  { word: 'dictionary', meaning: '辞書', note: '名詞' },
  { word: 'earth', meaning: '地球、土', note: '名詞' },
  { word: 'event', meaning: '出来事、行事', note: '名詞' },
  { word: 'experience', meaning: '経験、体験', note: '名詞' },
  { word: 'factory', meaning: '工場', note: '名詞' },
  { word: 'festival', meaning: '祭り', note: '名詞' },
  { word: 'flight', meaning: '飛行、フライト', note: '名詞' },
  { word: 'future', meaning: '未来、将来', note: '名詞' },
  { word: 'government', meaning: '政府', note: '名詞' },
  { word: 'history', meaning: '歴史', note: '名詞' },
  { word: 'hobby', meaning: '趣味', note: '名詞' },
  { word: 'hospital', meaning: '病院', note: '名詞' },
  { word: 'information', meaning: '情報', note: '名詞' },
  { word: 'journey', meaning: '旅行、旅', note: '名詞' },
  { word: 'accept', meaning: '受け入れる', note: '動詞' },
  { word: 'agree', meaning: '同意する', note: '動詞' },
  { word: 'allow', meaning: '許可する、許す', note: '動詞' },
  { word: 'appear', meaning: '現れる、～のように見える', note: '動詞' },
  { word: 'arrive', meaning: '到着する', note: '動詞' },
  { word: 'become', meaning: '～になる', note: '動詞' },
  { word: 'belong', meaning: '所属する（belong to ～：～に属する）', note: '動詞' },
  { word: 'borrow', meaning: '借りる', note: '動詞' },
  { word: 'bring', meaning: '持って来る', note: '動詞' },
  { word: 'build', meaning: '建てる、造る', note: '動詞' },
  { word: 'cancel', meaning: '取り消す、キャンセルする', note: '動詞' },
  { word: 'carry', meaning: '運ぶ、持ち歩く', note: '動詞' },
  { word: 'catch', meaning: '捕まえる、（電車などに）間に合う', note: '動詞' },
  { word: 'choose', meaning: '選ぶ', note: '動詞' },
  { word: 'collect', meaning: '集める', note: '動詞' },
  { word: 'continue', meaning: '続ける', note: '動詞' },
  { word: 'create', meaning: '創造する、作り出す', note: '動詞' },
  { word: 'decide', meaning: '決める、決意する', note: '動詞' },
  { word: 'describe', meaning: '描写する、説明する', note: '動詞' },
  { word: 'destroy', meaning: '破壊する', note: '動詞' },
  { word: 'discover', meaning: '発見する', note: '動詞' },
  { word: 'explain', meaning: '説明する', note: '動詞' },
  { word: 'forget', meaning: '忘れる', note: '動詞' },
  { word: 'happen', meaning: '起こる', note: '動詞' },
  { word: 'improve', meaning: '改善する、向上させる', note: '動詞' },
  { word: 'increase', meaning: '増える、増やす', note: '動詞' },
  { word: 'invite', meaning: '招待する', note: '動詞' },
  { word: 'join', meaning: '参加する、加わる', note: '動詞' },
  { word: 'leave', meaning: '出発する、残す、去る', note: '動詞' },
  { word: 'lend', meaning: '貸す', note: '動詞' },
  { word: 'notice', meaning: '気づく', note: '動詞' },
  { word: 'offer', meaning: '提供する、申し出る', note: '動詞' },
  { word: 'receive', meaning: '受け取る', note: '動詞' },
  { word: 'remember', meaning: '覚えておく、思い出す', note: '動詞' },
  { word: 'return', meaning: '戻る、返す', note: '動詞' },
  { word: 'abroad', meaning: '外国へ［で］（副）', note: '形容詞・副詞' },
  { word: 'almost', meaning: 'ほとんど（副）', note: '形容詞・副詞' },
  { word: 'already', meaning: 'すでに、もう（副）', note: '形容詞・副詞' },
  { word: 'ancient', meaning: '古代の（形）', note: '形容詞・副詞' },
  { word: 'awful', meaning: 'ひどい、嫌な（形）', note: '形容詞・副詞' },
  { word: 'convenient', meaning: '便利な（形）', note: '形容詞・副詞' },
  { word: 'crowded', meaning: '混雑した（形）', note: '形容詞・副詞' },
  { word: 'dangerous', meaning: '危険な（形）', note: '形容詞・副詞' },
  { word: 'different', meaning: '異なる、違う（形）', note: '形容詞・副詞' },
  { word: 'difficult', meaning: '難しい（形）', note: '形容詞・副詞' },
  { word: 'famous', meaning: '有名な（形）', note: '形容詞・副詞' },
  { word: 'foreign', meaning: '外国の（形）', note: '形容詞・副詞' },
  { word: 'important', meaning: '重要な（形）', note: '形容詞・副詞' },
  { word: 'impossible', meaning: '不可能な（形）', note: '形容詞・副詞' },
  { word: 'local', meaning: '地元の、地域の（形）', note: '形容詞・副詞' },
  { word: 'necessary', meaning: '必要な（形）', note: '形容詞・副詞' },
  { word: 'nervous', meaning: '緊張して、不安な（形）', note: '形容詞・副詞' },
  { word: 'particular', meaning: '特定の、特別な（形）', note: '形容詞・副詞' },
  { word: 'popular', meaning: '人気のある（形）', note: '形容詞・副詞' },
  { word: 'possible', meaning: '可能な（形）', note: '形容詞・副詞' },
  { word: 'quiet', meaning: '静かな（形）', note: '形容詞・副詞' },
  { word: 'several', meaning: 'いくつかの（形）', note: '形容詞・副詞' },
  { word: 'similar', meaning: '似ている（形）', note: '形容詞・副詞' },
  { word: 'traditional', meaning: '伝統的な（形）', note: '形容詞・副詞' },
  { word: 'useful', meaning: '役に立つ（形）', note: '形容詞・副詞' },
  { word: 'a few', meaning: 'いくつかの、少しの', note: '熟語・前置詞表現' },
  { word: 'a lot of', meaning: 'たくさんの', note: '熟語・前置詞表現' },
  { word: 'be able to', meaning: '～することができる', note: '熟語・前置詞表現' },
  { word: 'be interested in', meaning: '～に興味がある', note: '熟語・前置詞表現' },
  { word: 'for a long time', meaning: '長い間', note: '熟語・前置詞表現' },
  { word: 'give up', meaning: '諦める', note: '熟語・前置詞表現' },
  { word: 'look forward to', meaning: '～を楽しみに待つ', note: '熟語・前置詞表現' },
  { word: 'take care of', meaning: '～の世話をする', note: '熟語・前置詞表現' },
  { word: 'turn off', meaning: '（電気などを）消す', note: '熟語・前置詞表現' },
  { word: 'wake up', meaning: '目を覚ます、起きる', note: '熟語・前置詞表現' },
]
